---
apiVersion: v1
kind: Namespace
metadata:
  name: projectcontour
  labels:
    app.kubernetes.io/name: projectcontour
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour
  namespace: projectcontour
  labels:
    app.kubernetes.io/name: contour
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy
  namespace: projectcontour
  labels:
    app.kubernetes.io/name: envoy
